

version: '3.8'

services:
  web:
    build: ./djangobnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangobnb_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
  depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: djangobnb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
