# Generated by Django 5.0.2 on 2025-09-23 04:14

import useraccount.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', useraccount.models.CustomUserManager()),
            ],
        ),
    ]
