# Generated by Django 5.0.2 on 2025-09-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_resarvation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resarvation',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resarvation',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='resarvation',
            old_name='numbers_of_night',
            new_name='number_of_nights',
        ),
    ]
